name: Postman Tests

on:
  push:
  workflow_dispatch:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    env:
      COLLECTION: tests/collection.json
      REPORT_DIR: newman
      REPORT_FILE: newman-report.html
      SECRET_KEY: ${{ secrets.api_key }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: current

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Replace API key with GitHub Secret
        shell: bash
        run: |
          sed -i 's|"api_key":"[^"]*"|"api_key":"{{secret_key}}"|g' "$COLLECTION"
          sed -i 's|api_key=[^"& ]*|api_key={{secret_key}}|g' "$COLLECTION"

      - name: Run Postman tests
        continue-on-error: true
        run: |
          mkdir -p "$REPORT_DIR"
          newman run "$COLLECTION" \
            --env-var "secret_key=${SECRET_KEY}" \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export reports/index.html

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman/newman-report.html

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports

      - name: Fail pipeline if Newman failed
        if: steps.newman.outcome == 'failure'
        run: exit 1
