name: Postman API Tests (NASA)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman + htmlextra
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Create reports folder
        run: mkdir -p reports

      - name: Run Postman Collection
        run: |
          newman run postman/collection.json \
            ${{ hashFiles('postman/environment.json') != '' && format('-e postman/environment.json') || '' }} \
            --env-var "secret_key=${{ secrets.NASA_API_KEY }}" \
            --reporters cli,htmlextra,junit \
            --reporter-htmlextra-export reports/index.html \
            --reporter-htmlextra-title "NASA APOD API Tests" \
            --reporter-htmlextra-darkTheme \
            --reporter-junit-export reports/junit-report.xml

      - name: Upload reports as Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-reports
          path: reports/
          retention-days: 30

      - name: Commit report to reports/index.html
        if: always() && github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add reports/index.html reports/junit-report.xml || true

          if git diff --staged --quiet; then
            echo "Отчёт не изменился"
          else
            git pull --rebase origin main || true
            git commit -m "docs: update Postman test report [skip ci]"
            git push
          fi
